[package]
name = "http-server-arduino"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.20.0", features = ["full"]}
warp = "0.3.2"
tokio-serial = "5.4.3"
