# Don't print a new line at the start of the prompt
add_newline = false
format = "$all"

[line_break]
disabled = true
# git status
[git_status]
conflicted = "âš”ï¸ "
ahead = "Ã—${count} ï‚ª "
behind = "Ã—${count}ï‚« "
diverged = " Ã—${ahead_count} ğŸ¢ Ã—${behind_count}ğŸ”± ğŸï¸ ğŸ’¨"
untracked = "${count}x? "
stashed = "ğŸ“¦ "
modified = "${count}Ã—! "
staged = "${count}Ã—s "
renamed = "${count}Ã—r "
deleted = "${count}Ã—âœ˜ "
style = "bold red"
format = "[$all_status$ahead_behind]($style)"
